# Categorical Naive Bayes Classifier

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas
import numpy
import matplotlib.pyplot as plt
import itertools
import sklearn
from sklearn.metrics import log_loss

In [3]:
import loan_approval_lib
from loan_approval_lib import logspace, linspace

In [4]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.naive_bayes import CategoricalNB

In [5]:
data = loan_approval_lib.load_original_data()

In [6]:
data

person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0   
1              21           9600                   OWN                5.0   
2              25           9600              MORTGAGE                1.0   
3              23          65500                  RENT                4.0   
4              24          54400                  RENT                8.0   
...           ...            ...                   ...                ...   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  \
0             PERSONAL          D      35000          16.02   
1            EDUCATION          B       1000          11.14   
2              MEDICAL          C       5500          12.87   
3              MEDICAL          C      35000          15.23   
4              MEDICAL          C      35000          14.27   
...                ...        ...        ...            ...   
32576         PERSONAL          C       5800          13.16   
32577         PERSONAL          A      17625           7.49   
32578  HOMEIMPROVEMENT          B      35000          10.99   
32579         PERSONAL          B      15000          11.48   
32580          MEDICAL          B       6475           9.99   

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y   
1                     0.10                         N   
2                     0.57                         N   
3                     0.53                         N   
4                     0.55                         Y   
...                    ...                       ...   
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  loan_status  
0                               3            1  
1                               2            0  
2                               3            1  
3                               2            1  
4                               4            1  
...                           ...          ...  
32576                          30            0  
32577                          19            0  
32578                          28            1  
32579                          26            0  
32580                          30            0  

[32581 rows x 12 columns]

In [7]:
data_test = loan_approval_lib.load_data()['test']

In [8]:
data_test

id  person_age  person_income person_home_ownership  \
0      58645          23          69000                  RENT   
1      58646          26          96000              MORTGAGE   
2      58647          26          30000                  RENT   
3      58648          33          50000                  RENT   
4      58649          26         102000              MORTGAGE   
...      ...         ...            ...                   ...   
39093  97738          22          31200              MORTGAGE   
39094  97739          22          48000              MORTGAGE   
39095  97740          51          60000              MORTGAGE   
39096  97741          22          36000              MORTGAGE   
39097  97742          31          45000                  RENT   

       person_emp_length        loan_intent loan_grade  loan_amnt  \
0                    3.0    HOMEIMPROVEMENT          F      25000   
1                    6.0           PERSONAL          C      10000   
2                    5.0            VENTURE          E       4000   
3                    4.0  DEBTCONSOLIDATION          A       7000   
4                    8.0    HOMEIMPROVEMENT          D      15000   
...                  ...                ...        ...        ...   
39093                2.0  DEBTCONSOLIDATION          B       3000   
39094                6.0          EDUCATION          A       7000   
39095                0.0           PERSONAL          A      15000   
39096                4.0           PERSONAL          D      14000   
39097                6.0  DEBTCONSOLIDATION          B      19450   

       loan_int_rate  loan_percent_income cb_person_default_on_file  \
0              15.76                 0.36                         N   
1              12.68                 0.10                         Y   
2              17.19                 0.13                         Y   
3               8.90                 0.14                         N   
4              16.32                 0.15                         Y   
...              ...                  ...                       ...   
39093          10.37                 0.10                         N   
39094           6.03                 0.15                         N   
39095           7.51                 0.25                         N   
39096          15.62                 0.39                         Y   
39097           9.91                 0.44                         N   

       cb_person_cred_hist_length  
0                               2  
1                               4  
2                               2  
3                               7  
4                               4  
...                           ...  
39093                           4  
39094                           3  
39095                          25  
39096                           4  
39097                           9  

[39098 rows x 12 columns]

# Categorical NB Classifier

In [9]:
data_categorical = data[
    ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']
]

In [10]:
data_categorical

person_home_ownership      loan_intent loan_grade  \
0                      RENT         PERSONAL          D   
1                       OWN        EDUCATION          B   
2                  MORTGAGE          MEDICAL          C   
3                      RENT          MEDICAL          C   
4                      RENT          MEDICAL          C   
...                     ...              ...        ...   
32576              MORTGAGE         PERSONAL          C   
32577              MORTGAGE         PERSONAL          A   
32578                  RENT  HOMEIMPROVEMENT          B   
32579              MORTGAGE         PERSONAL          B   
32580                  RENT          MEDICAL          B   

      cb_person_default_on_file  
0                             Y  
1                             N  
2                             N  
3                             N  
4                             Y  
...                         ...  
32576                         N  
32577                         N  
32578                         N  
32579                         N  
32580                         N  

[32581 rows x 4 columns]

In [11]:
# nothing to do
data_categorical.isna().sum()

person_home_ownership        0
loan_intent                  0
loan_grade                   0
cb_person_default_on_file    0
dtype: int64

In [12]:
data_categorical.to_numpy()

array([['RENT', 'PERSONAL', 'D', 'Y'],
       ['OWN', 'EDUCATION', 'B', 'N'],
       ['MORTGAGE', 'MEDICAL', 'C', 'N'],
       ...,
       ['RENT', 'HOMEIMPROVEMENT', 'B', 'N'],
       ['MORTGAGE', 'PERSONAL', 'B', 'N'],
       ['RENT', 'MEDICAL', 'B', 'N']], shape=(32581, 4), dtype=object)

In [13]:
encoder = OrdinalEncoder()
encoder.fit(data_categorical.to_numpy())

OrdinalEncoder()

In [14]:
encoder.categories_

[array(['MORTGAGE', 'OTHER', 'OWN', 'RENT'], dtype=object),
 array(['DEBTCONSOLIDATION', 'EDUCATION', 'HOMEIMPROVEMENT', 'MEDICAL',
        'PERSONAL', 'VENTURE'], dtype=object),
 array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype=object),
 array(['N', 'Y'], dtype=object)]

In [15]:
data_categorical_encoded = encoder.transform(data_categorical.to_numpy())

In [16]:
data_categorical_encoded

array([[3., 4., 3., 1.],
       [2., 1., 1., 0.],
       [0., 3., 2., 0.],
       ...,
       [3., 2., 1., 0.],
       [0., 4., 1., 0.],
       [3., 3., 1., 0.]], shape=(32581, 4))

In [17]:
X = data_categorical_encoded
y = data['loan_status']

clf = CategoricalNB()
clf.fit(X, y)

CategoricalNB()

In [18]:
data_categorical_encoded[0, :].reshape(1, -1)

array([[3., 4., 3., 1.]])

In [19]:
clf.predict(data_categorical_encoded[0, :].reshape(1, -1))

array([1])

In [20]:
data['loan_status'][0]

np.int64(1)

In [21]:
data['loan_status_predict'] = clf.predict(data_categorical_encoded)
data

person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0   
1              21           9600                   OWN                5.0   
2              25           9600              MORTGAGE                1.0   
3              23          65500                  RENT                4.0   
4              24          54400                  RENT                8.0   
...           ...            ...                   ...                ...   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  \
0             PERSONAL          D      35000          16.02   
1            EDUCATION          B       1000          11.14   
2              MEDICAL          C       5500          12.87   
3              MEDICAL          C      35000          15.23   
4              MEDICAL          C      35000          14.27   
...                ...        ...        ...            ...   
32576         PERSONAL          C       5800          13.16   
32577         PERSONAL          A      17625           7.49   
32578  HOMEIMPROVEMENT          B      35000          10.99   
32579         PERSONAL          B      15000          11.48   
32580          MEDICAL          B       6475           9.99   

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y   
1                     0.10                         N   
2                     0.57                         N   
3                     0.53                         N   
4                     0.55                         Y   
...                    ...                       ...   
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  loan_status  loan_status_predict  
0                               3            1                    1  
1                               2            0                    0  
2                               3            1                    0  
3                               2            1                    0  
4                               4            1                    1  
...                           ...          ...                  ...  
32576                          30            0                    0  
32577                          19            0                    0  
32578                          28            1                    0  
32579                          26            0                    0  
32580                          30            0                    0  

[32581 rows x 13 columns]

In [29]:
P = (data['loan_status'] == data['loan_status_predict']).sum() / len(data)
P

np.float64(0.8114852214480832)

In [22]:
data_test_categorical = data_test[
    ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']
]

In [23]:
data_test_categorical

person_home_ownership        loan_intent loan_grade  \
0                      RENT    HOMEIMPROVEMENT          F   
1                  MORTGAGE           PERSONAL          C   
2                      RENT            VENTURE          E   
3                      RENT  DEBTCONSOLIDATION          A   
4                  MORTGAGE    HOMEIMPROVEMENT          D   
...                     ...                ...        ...   
39093              MORTGAGE  DEBTCONSOLIDATION          B   
39094              MORTGAGE          EDUCATION          A   
39095              MORTGAGE           PERSONAL          A   
39096              MORTGAGE           PERSONAL          D   
39097                  RENT  DEBTCONSOLIDATION          B   

      cb_person_default_on_file  
0                             N  
1                             Y  
2                             Y  
3                             N  
4                             Y  
...                         ...  
39093                         N  
39094                         N  
39095                         N  
39096                         Y  
39097                         N  

[39098 rows x 4 columns]

In [24]:
data_test_categorical_encoded = encoder.transform(data_test_categorical.to_numpy())

In [25]:
data_test_categorical_encoded

array([[3., 2., 5., 0.],
       [0., 4., 2., 1.],
       [3., 5., 4., 1.],
       ...,
       [0., 4., 0., 0.],
       [0., 4., 3., 1.],
       [3., 0., 1., 0.]], shape=(39098, 4))

In [26]:
clf.predict(data_test_categorical_encoded)

array([1, 0, 1, ..., 0, 1, 0], shape=(39098,))

In [27]:
data_test_with_loan_status = data_test
data_test_with_loan_status['loan_status'] = clf.predict(data_test_categorical_encoded)

In [43]:
data_test_with_loan_status

id  person_age  person_income person_home_ownership  \
0      58645          23          69000                  RENT   
1      58646          26          96000              MORTGAGE   
2      58647          26          30000                  RENT   
3      58648          33          50000                  RENT   
4      58649          26         102000              MORTGAGE   
...      ...         ...            ...                   ...   
39093  97738          22          31200              MORTGAGE   
39094  97739          22          48000              MORTGAGE   
39095  97740          51          60000              MORTGAGE   
39096  97741          22          36000              MORTGAGE   
39097  97742          31          45000                  RENT   

       person_emp_length        loan_intent loan_grade  loan_amnt  \
0                    3.0    HOMEIMPROVEMENT          F      25000   
1                    6.0           PERSONAL          C      10000   
2                    5.0            VENTURE          E       4000   
3                    4.0  DEBTCONSOLIDATION          A       7000   
4                    8.0    HOMEIMPROVEMENT          D      15000   
...                  ...                ...        ...        ...   
39093                2.0  DEBTCONSOLIDATION          B       3000   
39094                6.0          EDUCATION          A       7000   
39095                0.0           PERSONAL          A      15000   
39096                4.0           PERSONAL          D      14000   
39097                6.0  DEBTCONSOLIDATION          B      19450   

       loan_int_rate  loan_percent_income cb_person_default_on_file  \
0              15.76                 0.36                         N   
1              12.68                 0.10                         Y   
2              17.19                 0.13                         Y   
3               8.90                 0.14                         N   
4              16.32                 0.15                         Y   
...              ...                  ...                       ...   
39093          10.37                 0.10                         N   
39094           6.03                 0.15                         N   
39095           7.51                 0.25                         N   
39096          15.62                 0.39                         Y   
39097           9.91                 0.44                         N   

       cb_person_cred_hist_length  loan_status  
0                               2            1  
1                               4            0  
2                               2            1  
3                               7            0  
4                               4            1  
...                           ...          ...  
39093                           4            0  
39094                           3            0  
39095                          25            0  
39096                           4            1  
39097                           9            0  

[39098 rows x 13 columns]

In [44]:
data_test_with_loan_status[['id', 'loan_status']].to_csv(
    'data_test_predict-categorical_NB.csv',
    index=False,
)

See the "simple model" Notebook files for the next steps